platforms = ["claude", "gemini", "antigravity", "opencode", "codex"]

instructions = "~/dotfiles/ai/instructions/AGENTS.md"

[deps]
angular-skills = "https://github.com/angular/skills"
material-3-skills = "https://github.com/hamen/material-3-skill"
android-skills = "https://github.com/android/skills"
stitch-skills = "https://github.com/google-labs-code/stitch-skills"

[skills]
paths = [
  "~/dotfiles/ai/skills/*",
  "~/.gemini/extensions/workspace/skills/*",
  "@material-3-skills",
  "@angular-skills/*",
  "@android-skills/system/*",
  "@android-skills/navigation/*",
  "@android-skills/performance/*",
  "@stitch-skills/skills/design-md",
  "@stitch-skills/skills/taste-design",
  "@stitch-skills/skills/enhance-prompt",
]

[subagents]
paths = ["~/dotfiles/ai/subagents/*"]

[mcp.angular-cli]
command = "npx"
args = ["-y", "@angular/cli", "mcp"]

[mcp.gcloud]
command = "npx"
args = ["-y", "@google-cloud/gcloud-mcp"]

[mcp.pencil]
command = "/Applications/Pencil.app/Contents/Resources/app.asar.unpacked/out/mcp-server-darwin-arm64"
args = ["--app", "desktop"]

[mcp.cloud-run]
command = "npx"
args = ["-y", "@google-cloud/cloud-run-mcp"]

[mcp.firebase-mcp-server]
command = "npx"
args = ["-y", "firebase-tools@latest", "mcp"]

[gemini.extensions]
workspace = "https://github.com/gemini-cli-extensions/workspace"
