# User configuration

export EDITOR='nvim'

# Git aliases
alias g='git'
alias ga='git add'
alias gc='git commit -v'
alias gd='git diff'
alias gf='git fetch'
alias glgg='git log --graph'
alias grmc='git rm --cached'
alias gst='git status'
alias gp='git push'
# Branch Management
alias gsw='git switch'
alias gsc='git switch -c'  # Think "Switch & Create"
alias gsm='git switch main' # Quick jump to main/master
# File Recovery (The other half of checkout)
alias grs='git restore'
alias grss='git restore --staged' # To unstage files

# History configuration
HISTFILE=${HOME}/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# Paths
if [[ $OSTYPE = (linux)* ]]; then
  export ANDROID_HOME="$HOME/Android/Sdk"
  open() {
    xdg-open "${@:-.}" &>/dev/null
  }
else
  export ANDROID_HOME="$HOME/Library/Android/sdk"
fi
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Google Cloud
export PATH=/opt/homebrew/share/google-cloud-sdk/bin:"$PATH"
# Go
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
# Cargo
export PATH="$HOME/.cargo/bin:$PATH"
# Bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
# Local bin
export PATH="$HOME/.local/bin:$PATH"

# Lang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# GitHub Credentials
GITHUB_USERNAME=charliesbot

if [[ "$(uname)" == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
  test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Enable FZF if present
if command -v fzf >/dev/null 2>&1; then
  source <(fzf --zsh)
fi

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)

export FZF_DEFAULT_COMMAND='rg --files --fixed-strings --hidden --follow --glob "!.git/*"'

# OpenCode
export PATH="$HOME/.opencode/bin:$PATH"

# Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"
